export type IconType =
  'icon-fenxiang' |
  'icon-shezhi' |
  'icon-shezhi2' |
  'icon-tuandui1' |
  'icon-mingxinghuodong' |
  'icon-shezhi3' |
  'icon-yijianfankui1' |
  'icon-ziliao1' |
  'icon-nv' |
  'icon-nan' |
  'icon-youjiantou' |
  'icon-jichu_zhiding' |
  'icon-chakan' |
  'icon-dingwei' |
  'icon-shijian' |
  'icon-bianji' |
  'icon-xiajiantou-' |
  'icon-biaoqing' |
  'icon-plus-circle' |
  'icon-yuyin' |
  'icon-jianpan' |
  'icon-tupian' |
  'icon-yaoyue_hor' |
  'icon-queren' |
  'icon-yichexiao' |
  'icon-shoujishumadiannao' |
  'icon-lvzhou_zhongduan_shouji' |
  'icon-tuichu' |
  'icon-pingban' |
  'icon-biaojiyidu2' |
  'icon-miandarao' |
  'icon-tongzhi' |
  'icon-shenqingzhong' |
  'icon-shibai' |
  'icon-liaotian' |
  'icon-fuwutai02' |
  'icon-jubao' |
  'icon-weirenzheng' |
  'icon-yirenzheng' |
  'icon-fangwurenzheng' |
  'icon-qicherenzheng' |
  'icon-shimingrenzheng' |
  'icon-ziliaorenzheng' |
  'icon-anquanrenzheng' |
  'icon-yinhangkarenzheng' |
  'icon-close' |
  'icon-yaoqingjiaru' |
  'icon-yinhao' |
  'icon-position' |
  'icon-xueli' |
  'icon-qianbao' |
  'icon-shaixuan'

export interface IconTypeMap {
  'icon-fenxiang': true;
  'icon-shezhi': true;
  'icon-shezhi2': true;
  'icon-tuandui1': true;
  'icon-mingxinghuodong': true;
  'icon-shezhi3': true;
  'icon-yijianfankui1': true;
  'icon-ziliao1': true;
  'icon-nv': true;
  'icon-nan': true;
  'icon-youjiantou': true;
  'icon-jichu_zhiding': true;
  'icon-chakan': true;
  'icon-dingwei': true;
  'icon-shijian': true;
  'icon-bianji': true;
  'icon-xiajiantou-': true;
  'icon-biaoqing': true;
  'icon-plus-circle': true;
  'icon-yuyin': true;
  'icon-jianpan': true;
  'icon-tupian': true;
  'icon-yaoyue_hor': true;
  'icon-queren': true;
  'icon-yichexiao': true;
  'icon-shoujishumadiannao': true;
  'icon-lvzhou_zhongduan_shouji': true;
  'icon-tuichu': true;
  'icon-pingban': true;
  'icon-biaojiyidu2': true;
  'icon-miandarao': true;
  'icon-tongzhi': true;
  'icon-shenqingzhong': true;
  'icon-shibai': true;
  'icon-liaotian': true;
  'icon-fuwutai02': true;
  'icon-jubao': true;
  'icon-weirenzheng': true;
  'icon-yirenzheng': true;
  'icon-fangwurenzheng': true;
  'icon-qicherenzheng': true;
  'icon-shimingrenzheng': true;
  'icon-ziliaorenzheng': true;
  'icon-anquanrenzheng': true;
  'icon-yinhangkarenzheng': true;
  'icon-close': true;
  'icon-yaoqingjiaru': true;
  'icon-yinhao': true;
  'icon-position': true;
  'icon-xueli': true;
  'icon-qianbao': true;
  'icon-shaixuan': true
}
